name: Cypress E2E test
on:
  pull_request:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Start Server
        run: npm run start-server
        working-directory: /server
      - name: config
        run: |
          pwd
      - name: Run e2e test
        uses: cypress-io/github-action@v5.0.8
        with:
          run: npm run e2e-test
        working-directory: /client
        